# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_6.ui'
#
# Created: Sun Aug  3 18:33:17 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MyForm(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(782, 596)
        self.allTabWidget = QtGui.QTabWidget(main_window)
        self.allTabWidget.setGeometry(QtCore.QRect(-3, -2, 791, 601))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.allTabWidget.setFont(font)
        self.allTabWidget.setAutoFillBackground(False)
        self.allTabWidget.setObjectName(_fromUtf8("allTabWidget"))
        self.tab_login = QtGui.QWidget()
        self.tab_login.setObjectName(_fromUtf8("tab_login"))
        self.login_group = QtGui.QGroupBox(self.tab_login)
        self.login_group.setGeometry(QtCore.QRect(160, 209, 431, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_group.setFont(font)
        self.login_group.setAutoFillBackground(True)
        self.login_group.setObjectName(_fromUtf8("login_group"))
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.login_group)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 30, 161, 101))
        self.verticalLayoutWidget_10.setObjectName(_fromUtf8("verticalLayoutWidget_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.login_login_label = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.login_login_label.setObjectName(_fromUtf8("login_login_label"))
        self.verticalLayout_10.addWidget(self.login_login_label)
        self.login_pass_label = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.login_pass_label.setObjectName(_fromUtf8("login_pass_label"))
        self.verticalLayout_10.addWidget(self.login_pass_label)
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.login_group)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(190, 30, 231, 101))
        self.verticalLayoutWidget_11.setObjectName(_fromUtf8("verticalLayoutWidget_11"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.login_login = QtGui.QLineEdit(self.verticalLayoutWidget_11)
        self.login_login.setObjectName(_fromUtf8("login_login"))
        self.verticalLayout_18.addWidget(self.login_login)
        self.login_pass = QtGui.QLineEdit(self.verticalLayoutWidget_11)
        self.login_pass.setObjectName(_fromUtf8("login_pass"))
        self.verticalLayout_18.addWidget(self.login_pass)
        self.login_progressBar = QtGui.QProgressBar(self.login_group)
        self.login_progressBar.setGeometry(QtCore.QRect(12, 240, 411, 20))
        self.login_progressBar.setProperty("value", 0)
        self.login_progressBar.setObjectName(_fromUtf8("login_progressBar"))
        self.login_info_label = QtGui.QLabel(self.login_group)
        self.login_info_label.setGeometry(QtCore.QRect(10, 200, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_info_label.setFont(font)
        self.login_info_label.setText(_fromUtf8(""))
        self.login_info_label.setObjectName(_fromUtf8("login_info_label"))
        self.login_reset = QtGui.QPushButton(self.login_group)
        self.login_reset.setGeometry(QtCore.QRect(270, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_reset.setFont(font)
        self.login_reset.setObjectName(_fromUtf8("login_reset"))
        self.login_enter = QtGui.QPushButton(self.login_group)
        self.login_enter.setGeometry(QtCore.QRect(10, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_enter.setFont(font)
        self.login_enter.setStyleSheet(_fromUtf8(""))
        self.login_enter.setObjectName(_fromUtf8("login_enter"))
        self.login_label_persona = QtGui.QLabel(self.tab_login)
        self.login_label_persona.setGeometry(QtCore.QRect(230, 68, 331, 81))
        self.login_label_persona.setText(_fromUtf8(""))
        self.login_label_persona.setObjectName(_fromUtf8("login_label_persona"))
        self.allTabWidget.addTab(self.tab_login, _fromUtf8(""))
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName(_fromUtf8("tab_input"))
        self.pers_input_group = QtGui.QGroupBox(self.tab_input)
        self.pers_input_group.setGeometry(QtCore.QRect(20, 10, 411, 301))
        self.pers_input_group.setAutoFillBackground(True)
        self.pers_input_group.setObjectName(_fromUtf8("pers_input_group"))
        self.verticalLayoutWidget = QtGui.QWidget(self.pers_input_group)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 130, 271))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.name_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.name_input_label.setObjectName(_fromUtf8("name_input_label"))
        self.verticalLayout.addWidget(self.name_input_label)
        self.sur_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.sur_input_label.setObjectName(_fromUtf8("sur_input_label"))
        self.verticalLayout.addWidget(self.sur_input_label)
        self.name_lat_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.name_lat_input_label.setObjectName(_fromUtf8("name_lat_input_label"))
        self.verticalLayout.addWidget(self.name_lat_input_label)
        self.sur_lat_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.sur_lat_input_label.setObjectName(_fromUtf8("sur_lat_input_label"))
        self.verticalLayout.addWidget(self.sur_lat_input_label)
        self.birth_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.birth_input_label.setObjectName(_fromUtf8("birth_input_label"))
        self.verticalLayout.addWidget(self.birth_input_label)
        self.civil_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.civil_input_label.setObjectName(_fromUtf8("civil_input_label"))
        self.verticalLayout.addWidget(self.civil_input_label)
        self.pass_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.pass_input_label.setObjectName(_fromUtf8("pass_input_label"))
        self.verticalLayout.addWidget(self.pass_input_label)
        self.number_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.number_input_label.setObjectName(_fromUtf8("number_input_label"))
        self.verticalLayout.addWidget(self.number_input_label)
        self.auto_input_label = QtGui.QLabel(self.verticalLayoutWidget)
        self.auto_input_label.setObjectName(_fromUtf8("auto_input_label"))
        self.verticalLayout.addWidget(self.auto_input_label)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.pers_input_group)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 20, 261, 275))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.name_input = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.name_input.setObjectName(_fromUtf8("name_input"))
        self.verticalLayout_2.addWidget(self.name_input)
        self.sur_input = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.sur_input.setObjectName(_fromUtf8("sur_input"))
        self.verticalLayout_2.addWidget(self.sur_input)
        self.name_lat_input = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.name_lat_input.setObjectName(_fromUtf8("name_lat_input"))
        self.verticalLayout_2.addWidget(self.name_lat_input)
        self.sur_lat_input = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.sur_lat_input.setObjectName(_fromUtf8("sur_lat_input"))
        self.verticalLayout_2.addWidget(self.sur_lat_input)
        self.birth_input = QtGui.QDateEdit(self.verticalLayoutWidget_2)
        self.birth_input.setObjectName(_fromUtf8("birth_input"))
        self.verticalLayout_2.addWidget(self.birth_input)
        self.civil_input = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.civil_input.setObjectName(_fromUtf8("civil_input"))
        self.verticalLayout_2.addWidget(self.civil_input)
        self.pass_input = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.pass_input.setObjectName(_fromUtf8("pass_input"))
        self.verticalLayout_2.addWidget(self.pass_input)
        self.number_input = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.number_input.setObjectName(_fromUtf8("number_input"))
        self.verticalLayout_2.addWidget(self.number_input)
        self.number_auto_input = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.number_auto_input.setObjectName(_fromUtf8("number_auto_input"))
        self.verticalLayout_2.addWidget(self.number_auto_input)
        self.info_input_group = QtGui.QGroupBox(self.tab_input)
        self.info_input_group.setGeometry(QtCore.QRect(20, 320, 411, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.info_input_group.setFont(font)
        self.info_input_group.setAutoFillBackground(True)
        self.info_input_group.setObjectName(_fromUtf8("info_input_group"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.info_input_group)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 204, 151))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.info_date_input_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.info_date_input_label.setObjectName(_fromUtf8("info_date_input_label"))
        self.verticalLayout_5.addWidget(self.info_date_input_label)
        self.info_country_input_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.info_country_input_label.setObjectName(_fromUtf8("info_country_input_label"))
        self.verticalLayout_5.addWidget(self.info_country_input_label)
        self.info_dir_input_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.info_dir_input_label.setObjectName(_fromUtf8("info_dir_input_label"))
        self.verticalLayout_5.addWidget(self.info_dir_input_label)
        self.info_ppr_input_label = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.info_ppr_input_label.setChecked(True)
        self.info_ppr_input_label.setObjectName(_fromUtf8("info_ppr_input_label"))
        self.verticalLayout_5.addWidget(self.info_ppr_input_label)
        self.info_who_input_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.info_who_input_label.setObjectName(_fromUtf8("info_who_input_label"))
        self.verticalLayout_5.addWidget(self.info_who_input_label)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.info_input_group)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(210, 20, 191, 151))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.info_dir_input = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.info_dir_input.setMargin(0)
        self.info_dir_input.setObjectName(_fromUtf8("info_dir_input"))
        self.info_date_input = QtGui.QDateEdit(self.verticalLayoutWidget_6)
        self.info_date_input.setObjectName(_fromUtf8("info_date_input"))
        self.info_dir_input.addWidget(self.info_date_input)
        self.info_country_input = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.info_country_input.setObjectName(_fromUtf8("info_country_input"))
        self.info_dir_input.addWidget(self.info_country_input)
        self.dir_group_input = QtGui.QHBoxLayout()
        self.dir_group_input.setObjectName(_fromUtf8("dir_group_input"))
        self.info_dir_input_in = QtGui.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_dir_input_in.setFont(font)
        self.info_dir_input_in.setAutoFillBackground(False)
        self.info_dir_input_in.setStyleSheet(_fromUtf8(""))
        self.info_dir_input_in.setObjectName(_fromUtf8("info_dir_input_in"))
        self.dir_group_input.addWidget(self.info_dir_input_in)
        self.info_dir_input_out = QtGui.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_dir_input_out.setFont(font)
        self.info_dir_input_out.setStyleSheet(_fromUtf8(""))
        self.info_dir_input_out.setObjectName(_fromUtf8("info_dir_input_out"))
        self.dir_group_input.addWidget(self.info_dir_input_out)
        self.info_dir_input.addLayout(self.dir_group_input)
        self.info_ppr_input = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.info_ppr_input.setObjectName(_fromUtf8("info_ppr_input"))
        self.info_dir_input.addWidget(self.info_ppr_input)
        self.info_who_input = QtGui.QLineEdit(self.verticalLayoutWidget_6)
        self.info_who_input.setObjectName(_fromUtf8("info_who_input"))
        self.info_dir_input.addWidget(self.info_who_input)
        self.tmc_input_group = QtGui.QGroupBox(self.tab_input)
        self.tmc_input_group.setGeometry(QtCore.QRect(440, 10, 331, 121))
        self.tmc_input_group.setAutoFillBackground(True)
        self.tmc_input_group.setObjectName(_fromUtf8("tmc_input_group"))
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tmc_input_group)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 91, 91))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.tmc_label_group_input = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.tmc_label_group_input.setMargin(0)
        self.tmc_label_group_input.setObjectName(_fromUtf8("tmc_label_group_input"))
        self.sort_input_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.sort_input_label.setObjectName(_fromUtf8("sort_input_label"))
        self.tmc_label_group_input.addWidget(self.sort_input_label)
        self.quant_input_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.quant_input_label.setObjectName(_fromUtf8("quant_input_label"))
        self.tmc_label_group_input.addWidget(self.quant_input_label)
        self.price_input_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.price_input_label.setObjectName(_fromUtf8("price_input_label"))
        self.tmc_label_group_input.addWidget(self.price_input_label)
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.tmc_input_group)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(220, 50, 101, 61))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.tmc_group_input = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.tmc_group_input.setMargin(0)
        self.tmc_group_input.setObjectName(_fromUtf8("tmc_group_input"))
        self.quant_input = QtGui.QLineEdit(self.verticalLayoutWidget_8)
        self.quant_input.setObjectName(_fromUtf8("quant_input"))
        self.tmc_group_input.addWidget(self.quant_input)
        self.price_input = QtGui.QLineEdit(self.verticalLayoutWidget_8)
        self.price_input.setObjectName(_fromUtf8("price_input"))
        self.tmc_group_input.addWidget(self.price_input)
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.tmc_input_group)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(110, 50, 101, 61))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.tmc_select_group_input = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.tmc_select_group_input.setMargin(0)
        self.tmc_select_group_input.setObjectName(_fromUtf8("tmc_select_group_input"))
        self.quant_input_select = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.quant_input_select.setObjectName(_fromUtf8("quant_input_select"))
        self.tmc_select_group_input.addWidget(self.quant_input_select)
        self.price_input_select = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.price_input_select.setObjectName(_fromUtf8("price_input_select"))
        self.tmc_select_group_input.addWidget(self.price_input_select)
        self.sort_input = QtGui.QComboBox(self.tmc_input_group)
        self.sort_input.setGeometry(QtCore.QRect(110, 20, 211, 25))
        self.sort_input.setObjectName(_fromUtf8("sort_input"))
        self.fab_input_group = QtGui.QGroupBox(self.tab_input)
        self.fab_input_group.setGeometry(QtCore.QRect(440, 140, 331, 421))
        self.fab_input_group.setAcceptDrops(False)
        self.fab_input_group.setAutoFillBackground(True)
        self.fab_input_group.setFlat(False)
        self.fab_input_group.setCheckable(False)
        self.fab_input_group.setObjectName(_fromUtf8("fab_input_group"))
        self.fab_input_text = QtGui.QPlainTextEdit(self.fab_input_group)
        self.fab_input_text.setGeometry(QtCore.QRect(10, 30, 311, 381))
        self.fab_input_text.setObjectName(_fromUtf8("fab_input_text"))
        self.input_write = QtGui.QPushButton(self.tab_input)
        self.input_write.setGeometry(QtCore.QRect(20, 504, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_write.setFont(font)
        self.input_write.setStyleSheet(_fromUtf8(""))
        self.input_write.setObjectName(_fromUtf8("input_write"))
        self.input_reset = QtGui.QPushButton(self.tab_input)
        self.input_reset.setGeometry(QtCore.QRect(280, 504, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_reset.setFont(font)
        self.input_reset.setObjectName(_fromUtf8("input_reset"))
        self.intput_progressBar = QtGui.QProgressBar(self.tab_input)
        self.intput_progressBar.setGeometry(QtCore.QRect(20, 543, 411, 20))
        self.intput_progressBar.setProperty("value", 0)
        self.intput_progressBar.setObjectName(_fromUtf8("intput_progressBar"))
        self.allTabWidget.addTab(self.tab_input, _fromUtf8(""))
        self.tab_output = QtGui.QWidget()
        self.tab_output.setObjectName(_fromUtf8("tab_output"))
        self.pers_output_group = QtGui.QGroupBox(self.tab_output)
        self.pers_output_group.setGeometry(QtCore.QRect(20, 10, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pers_output_group.setFont(font)
        self.pers_output_group.setAutoFillBackground(True)
        self.pers_output_group.setObjectName(_fromUtf8("pers_output_group"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.pers_output_group)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 141, 51))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.sur_output_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sur_output_label.setFont(font)
        self.sur_output_label.setStyleSheet(_fromUtf8(""))
        self.sur_output_label.setObjectName(_fromUtf8("sur_output_label"))
        self.verticalLayout_3.addWidget(self.sur_output_label)
        self.sur_lat_output_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sur_lat_output_label.setFont(font)
        self.sur_lat_output_label.setStyleSheet(_fromUtf8(""))
        self.sur_lat_output_label.setObjectName(_fromUtf8("sur_lat_output_label"))
        self.verticalLayout_3.addWidget(self.sur_lat_output_label)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.pers_output_group)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(160, 20, 161, 58))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.sur_output = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.sur_output.setObjectName(_fromUtf8("sur_output"))
        self.verticalLayout_4.addWidget(self.sur_output)
        self.sur_lat_output = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.sur_lat_output.setObjectName(_fromUtf8("sur_lat_output"))
        self.verticalLayout_4.addWidget(self.sur_lat_output)
        self.output_data_group = QtGui.QGroupBox(self.tab_output)
        self.output_data_group.setGeometry(QtCore.QRect(360, 10, 421, 451))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.output_data_group.setFont(font)
        self.output_data_group.setAutoFillBackground(True)
        self.output_data_group.setObjectName(_fromUtf8("output_data_group"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.output_data_group)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 401, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.output_data_total_group = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.output_data_total_group.setMargin(0)
        self.output_data_total_group.setObjectName(_fromUtf8("output_data_total_group"))
        self.output_data_total_label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.output_data_total_label.setObjectName(_fromUtf8("output_data_total_label"))
        self.output_data_total_group.addWidget(self.output_data_total_label)
        self.output_data_total = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.output_data_total.setObjectName(_fromUtf8("output_data_total"))
        self.output_data_total_group.addWidget(self.output_data_total)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.output_data_group)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 401, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.output_data_sur_label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.output_data_sur_label.setObjectName(_fromUtf8("output_data_sur_label"))
        self.horizontalLayout_2.addWidget(self.output_data_sur_label)
        self.output_data_sur = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.output_data_sur.setObjectName(_fromUtf8("output_data_sur"))
        self.horizontalLayout_2.addWidget(self.output_data_sur)
        self.output_data_text = QtGui.QPlainTextEdit(self.output_data_group)
        self.output_data_text.setGeometry(QtCore.QRect(10, 100, 401, 341))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.output_data_text.setFont(font)
        self.output_data_text.setObjectName(_fromUtf8("output_data_text"))
        self.output_find_ppr = QtGui.QPushButton(self.tab_output)
        self.output_find_ppr.setGeometry(QtCore.QRect(20, 409, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_find_ppr.setFont(font)
        self.output_find_ppr.setObjectName(_fromUtf8("output_find_ppr"))
        self.output_progressBar = QtGui.QProgressBar(self.tab_output)
        self.output_progressBar.setGeometry(QtCore.QRect(360, 543, 411, 20))
        self.output_progressBar.setProperty("value", 0)
        self.output_progressBar.setObjectName(_fromUtf8("output_progressBar"))
        self.pers_output_group_2 = QtGui.QGroupBox(self.tab_output)
        self.pers_output_group_2.setGeometry(QtCore.QRect(20, 130, 331, 81))
        self.pers_output_group_2.setAutoFillBackground(True)
        self.pers_output_group_2.setObjectName(_fromUtf8("pers_output_group_2"))
        self.verticalLayoutWidget_12 = QtGui.QWidget(self.pers_output_group_2)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 20, 143, 51))
        self.verticalLayoutWidget_12.setObjectName(_fromUtf8("verticalLayoutWidget_12"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pass_output_label = QtGui.QLabel(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pass_output_label.setFont(font)
        self.pass_output_label.setStyleSheet(_fromUtf8(""))
        self.pass_output_label.setObjectName(_fromUtf8("pass_output_label"))
        self.verticalLayout_12.addWidget(self.pass_output_label)
        self.auto_output_label = QtGui.QLabel(self.verticalLayoutWidget_12)
        self.auto_output_label.setObjectName(_fromUtf8("auto_output_label"))
        self.verticalLayout_12.addWidget(self.auto_output_label)
        self.verticalLayoutWidget_13 = QtGui.QWidget(self.pers_output_group_2)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(160, 20, 161, 58))
        self.verticalLayoutWidget_13.setObjectName(_fromUtf8("verticalLayoutWidget_13"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.pass_output = QtGui.QLineEdit(self.verticalLayoutWidget_13)
        self.pass_output.setObjectName(_fromUtf8("pass_output"))
        self.verticalLayout_13.addWidget(self.pass_output)
        self.auto_output = QtGui.QLineEdit(self.verticalLayoutWidget_13)
        self.auto_output.setObjectName(_fromUtf8("auto_output"))
        self.verticalLayout_13.addWidget(self.auto_output)
        self.output_reset_ppr = QtGui.QPushButton(self.tab_output)
        self.output_reset_ppr.setGeometry(QtCore.QRect(240, 409, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_reset_ppr.setFont(font)
        self.output_reset_ppr.setObjectName(_fromUtf8("output_reset_ppr"))
        self.output_find_sur = QtGui.QPushButton(self.tab_output)
        self.output_find_sur.setGeometry(QtCore.QRect(20, 98, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_find_sur.setFont(font)
        self.output_find_sur.setObjectName(_fromUtf8("output_find_sur"))
        self.output_reset_sur = QtGui.QPushButton(self.tab_output)
        self.output_reset_sur.setGeometry(QtCore.QRect(241, 98, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_reset_sur.setFont(font)
        self.output_reset_sur.setObjectName(_fromUtf8("output_reset_sur"))
        self.output_find_num = QtGui.QPushButton(self.tab_output)
        self.output_find_num.setGeometry(QtCore.QRect(20, 219, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_find_num.setFont(font)
        self.output_find_num.setObjectName(_fromUtf8("output_find_num"))
        self.output_reset_num = QtGui.QPushButton(self.tab_output)
        self.output_reset_num.setGeometry(QtCore.QRect(242, 219, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_reset_num.setFont(font)
        self.output_reset_num.setObjectName(_fromUtf8("output_reset_num"))
        self.info_output_group_2 = QtGui.QGroupBox(self.tab_output)
        self.info_output_group_2.setGeometry(QtCore.QRect(20, 260, 331, 141))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.info_output_group_2.setFont(font)
        self.info_output_group_2.setAutoFillBackground(True)
        self.info_output_group_2.setObjectName(_fromUtf8("info_output_group_2"))
        self.verticalLayoutWidget_21 = QtGui.QWidget(self.info_output_group_2)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(10, 20, 161, 111))
        self.verticalLayoutWidget_21.setObjectName(_fromUtf8("verticalLayoutWidget_21"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.info_date_output_label_from = QtGui.QLabel(self.verticalLayoutWidget_21)
        self.info_date_output_label_from.setObjectName(_fromUtf8("info_date_output_label_from"))
        self.verticalLayout_14.addWidget(self.info_date_output_label_from)
        self.info_date_output_label_to = QtGui.QLabel(self.verticalLayoutWidget_21)
        self.info_date_output_label_to.setObjectName(_fromUtf8("info_date_output_label_to"))
        self.verticalLayout_14.addWidget(self.info_date_output_label_to)
        self.info_ppr_output_label = QtGui.QCheckBox(self.verticalLayoutWidget_21)
        self.info_ppr_output_label.setChecked(True)
        self.info_ppr_output_label.setObjectName(_fromUtf8("info_ppr_output_label"))
        self.verticalLayout_14.addWidget(self.info_ppr_output_label)
        self.info_dir_output_label = QtGui.QLabel(self.verticalLayoutWidget_21)
        self.info_dir_output_label.setObjectName(_fromUtf8("info_dir_output_label"))
        self.verticalLayout_14.addWidget(self.info_dir_output_label)
        self.verticalLayoutWidget_23 = QtGui.QWidget(self.info_output_group_2)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(180, 20, 141, 120))
        self.verticalLayoutWidget_23.setObjectName(_fromUtf8("verticalLayoutWidget_23"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.info_date_output_from = QtGui.QDateEdit(self.verticalLayoutWidget_23)
        self.info_date_output_from.setObjectName(_fromUtf8("info_date_output_from"))
        self.verticalLayout_11.addWidget(self.info_date_output_from)
        self.info_date_output_to = QtGui.QDateEdit(self.verticalLayoutWidget_23)
        self.info_date_output_to.setObjectName(_fromUtf8("info_date_output_to"))
        self.verticalLayout_11.addWidget(self.info_date_output_to)
        self.info_ppr_output = QtGui.QComboBox(self.verticalLayoutWidget_23)
        self.info_ppr_output.setObjectName(_fromUtf8("info_ppr_output"))
        self.verticalLayout_11.addWidget(self.info_ppr_output)
        self.dir_group_output_2 = QtGui.QHBoxLayout()
        self.dir_group_output_2.setObjectName(_fromUtf8("dir_group_output_2"))
        self.info_dir_output_in = QtGui.QRadioButton(self.verticalLayoutWidget_23)
        self.info_dir_output_in.setObjectName(_fromUtf8("info_dir_output_in"))
        self.dir_group_output_2.addWidget(self.info_dir_output_in)
        self.info_dir_output_out = QtGui.QRadioButton(self.verticalLayoutWidget_23)
        self.info_dir_output_out.setObjectName(_fromUtf8("info_dir_output_out"))
        self.dir_group_output_2.addWidget(self.info_dir_output_out)
        self.verticalLayout_11.addLayout(self.dir_group_output_2)
        self.output_find_all = QtGui.QPushButton(self.tab_output)
        self.output_find_all.setGeometry(QtCore.QRect(359, 471, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_find_all.setFont(font)
        self.output_find_all.setObjectName(_fromUtf8("output_find_all"))
        self.output_reset_output = QtGui.QPushButton(self.tab_output)
        self.output_reset_output.setGeometry(QtCore.QRect(359, 506, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_reset_output.setFont(font)
        self.output_reset_output.setObjectName(_fromUtf8("output_reset_output"))
        self.output_export = QtGui.QPushButton(self.tab_output)
        self.output_export.setGeometry(QtCore.QRect(610, 471, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_export.setFont(font)
        self.output_export.setObjectName(_fromUtf8("output_export"))
        self.output_export_pdf = QtGui.QPushButton(self.tab_output)
        self.output_export_pdf.setGeometry(QtCore.QRect(610, 506, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_export_pdf.setFont(font)
        self.output_export_pdf.setObjectName(_fromUtf8("output_export_pdf"))
        self.info_output_group_date = QtGui.QGroupBox(self.tab_output)
        self.info_output_group_date.setGeometry(QtCore.QRect(20, 440, 331, 91))
        self.info_output_group_date.setAutoFillBackground(True)
        self.info_output_group_date.setObjectName(_fromUtf8("info_output_group_date"))
        self.verticalLayoutWidget_22 = QtGui.QWidget(self.info_output_group_date)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(10, 20, 161, 61))
        self.verticalLayoutWidget_22.setObjectName(_fromUtf8("verticalLayoutWidget_22"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.info_date_output_date_label_from = QtGui.QLabel(self.verticalLayoutWidget_22)
        self.info_date_output_date_label_from.setObjectName(_fromUtf8("info_date_output_date_label_from"))
        self.verticalLayout_15.addWidget(self.info_date_output_date_label_from)
        self.info_date_output_date_label_to = QtGui.QLabel(self.verticalLayoutWidget_22)
        self.info_date_output_date_label_to.setObjectName(_fromUtf8("info_date_output_date_label_to"))
        self.verticalLayout_15.addWidget(self.info_date_output_date_label_to)
        self.verticalLayoutWidget_24 = QtGui.QWidget(self.info_output_group_date)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(180, 20, 141, 61))
        self.verticalLayoutWidget_24.setObjectName(_fromUtf8("verticalLayoutWidget_24"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.info_date_output_date_from = QtGui.QDateEdit(self.verticalLayoutWidget_24)
        self.info_date_output_date_from.setObjectName(_fromUtf8("info_date_output_date_from"))
        self.verticalLayout_16.addWidget(self.info_date_output_date_from)
        self.info_date_output_date_to = QtGui.QDateEdit(self.verticalLayoutWidget_24)
        self.info_date_output_date_to.setObjectName(_fromUtf8("info_date_output_date_to"))
        self.verticalLayout_16.addWidget(self.info_date_output_date_to)
        self.output_reset_date = QtGui.QPushButton(self.tab_output)
        self.output_reset_date.setGeometry(QtCore.QRect(240, 532, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_reset_date.setFont(font)
        self.output_reset_date.setObjectName(_fromUtf8("output_reset_date"))
        self.output_find_date = QtGui.QPushButton(self.tab_output)
        self.output_find_date.setGeometry(QtCore.QRect(20, 532, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_find_date.setFont(font)
        self.output_find_date.setObjectName(_fromUtf8("output_find_date"))
        self.allTabWidget.addTab(self.tab_output, _fromUtf8(""))
        self.tab_edit = QtGui.QWidget()
        self.tab_edit.setObjectName(_fromUtf8("tab_edit"))
        self.pers_edit_group = QtGui.QGroupBox(self.tab_edit)
        self.pers_edit_group.setGeometry(QtCore.QRect(20, 10, 411, 301))
        self.pers_edit_group.setAutoFillBackground(True)
        self.pers_edit_group.setObjectName(_fromUtf8("pers_edit_group"))
        self.verticalLayoutWidget_120 = QtGui.QWidget(self.pers_edit_group)
        self.verticalLayoutWidget_120.setGeometry(QtCore.QRect(10, 20, 130, 271))
        self.verticalLayoutWidget_120.setObjectName(_fromUtf8("verticalLayoutWidget_120"))
        self.verticalLayout_92 = QtGui.QVBoxLayout(self.verticalLayoutWidget_120)
        self.verticalLayout_92.setMargin(0)
        self.verticalLayout_92.setObjectName(_fromUtf8("verticalLayout_92"))
        self.name_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.name_edit_label.setObjectName(_fromUtf8("name_edit_label"))
        self.verticalLayout_92.addWidget(self.name_edit_label)
        self.sur_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.sur_edit_label.setObjectName(_fromUtf8("sur_edit_label"))
        self.verticalLayout_92.addWidget(self.sur_edit_label)
        self.name_lat_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.name_lat_edit_label.setObjectName(_fromUtf8("name_lat_edit_label"))
        self.verticalLayout_92.addWidget(self.name_lat_edit_label)
        self.sur_lat_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.sur_lat_edit_label.setObjectName(_fromUtf8("sur_lat_edit_label"))
        self.verticalLayout_92.addWidget(self.sur_lat_edit_label)
        self.birth_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.birth_edit_label.setObjectName(_fromUtf8("birth_edit_label"))
        self.verticalLayout_92.addWidget(self.birth_edit_label)
        self.civil_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.civil_edit_label.setObjectName(_fromUtf8("civil_edit_label"))
        self.verticalLayout_92.addWidget(self.civil_edit_label)
        self.pass_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.pass_edit_label.setObjectName(_fromUtf8("pass_edit_label"))
        self.verticalLayout_92.addWidget(self.pass_edit_label)
        self.number_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.number_edit_label.setObjectName(_fromUtf8("number_edit_label"))
        self.verticalLayout_92.addWidget(self.number_edit_label)
        self.auto_edit_label = QtGui.QLabel(self.verticalLayoutWidget_120)
        self.auto_edit_label.setObjectName(_fromUtf8("auto_edit_label"))
        self.verticalLayout_92.addWidget(self.auto_edit_label)
        self.verticalLayoutWidget_121 = QtGui.QWidget(self.pers_edit_group)
        self.verticalLayoutWidget_121.setGeometry(QtCore.QRect(140, 20, 261, 275))
        self.verticalLayoutWidget_121.setObjectName(_fromUtf8("verticalLayoutWidget_121"))
        self.verticalLayout_93 = QtGui.QVBoxLayout(self.verticalLayoutWidget_121)
        self.verticalLayout_93.setMargin(0)
        self.verticalLayout_93.setObjectName(_fromUtf8("verticalLayout_93"))
        self.name_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.name_edit.setObjectName(_fromUtf8("name_edit"))
        self.verticalLayout_93.addWidget(self.name_edit)
        self.sur_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.sur_edit.setObjectName(_fromUtf8("sur_edit"))
        self.verticalLayout_93.addWidget(self.sur_edit)
        self.name_lat_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.name_lat_edit.setObjectName(_fromUtf8("name_lat_edit"))
        self.verticalLayout_93.addWidget(self.name_lat_edit)
        self.sur_lat_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.sur_lat_edit.setObjectName(_fromUtf8("sur_lat_edit"))
        self.verticalLayout_93.addWidget(self.sur_lat_edit)
        self.birth_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.birth_edit.setObjectName(_fromUtf8("birth_edit"))
        self.verticalLayout_93.addWidget(self.birth_edit)
        self.civil_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.civil_edit.setObjectName(_fromUtf8("civil_edit"))
        self.verticalLayout_93.addWidget(self.civil_edit)
        self.pass_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.pass_edit.setObjectName(_fromUtf8("pass_edit"))
        self.verticalLayout_93.addWidget(self.pass_edit)
        self.number_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.number_edit.setObjectName(_fromUtf8("number_edit"))
        self.verticalLayout_93.addWidget(self.number_edit)
        self.number_auto_edit = QtGui.QLineEdit(self.verticalLayoutWidget_121)
        self.number_auto_edit.setObjectName(_fromUtf8("number_auto_edit"))
        self.verticalLayout_93.addWidget(self.number_auto_edit)
        self.info_edit_group = QtGui.QGroupBox(self.tab_edit)
        self.info_edit_group.setGeometry(QtCore.QRect(20, 320, 411, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.info_edit_group.setFont(font)
        self.info_edit_group.setAutoFillBackground(True)
        self.info_edit_group.setObjectName(_fromUtf8("info_edit_group"))
        self.verticalLayoutWidget_122 = QtGui.QWidget(self.info_edit_group)
        self.verticalLayoutWidget_122.setGeometry(QtCore.QRect(10, 20, 191, 151))
        self.verticalLayoutWidget_122.setObjectName(_fromUtf8("verticalLayoutWidget_122"))
        self.verticalLayout_94 = QtGui.QVBoxLayout(self.verticalLayoutWidget_122)
        self.verticalLayout_94.setMargin(0)
        self.verticalLayout_94.setObjectName(_fromUtf8("verticalLayout_94"))
        self.info_date_edit_label = QtGui.QLabel(self.verticalLayoutWidget_122)
        self.info_date_edit_label.setObjectName(_fromUtf8("info_date_edit_label"))
        self.verticalLayout_94.addWidget(self.info_date_edit_label)
        self.info_country_edit_label = QtGui.QLabel(self.verticalLayoutWidget_122)
        self.info_country_edit_label.setObjectName(_fromUtf8("info_country_edit_label"))
        self.verticalLayout_94.addWidget(self.info_country_edit_label)
        self.info_dir_edit_label = QtGui.QLabel(self.verticalLayoutWidget_122)
        self.info_dir_edit_label.setObjectName(_fromUtf8("info_dir_edit_label"))
        self.verticalLayout_94.addWidget(self.info_dir_edit_label)
        self.info_ppr_edit_label = QtGui.QLabel(self.verticalLayoutWidget_122)
        self.info_ppr_edit_label.setObjectName(_fromUtf8("info_ppr_edit_label"))
        self.verticalLayout_94.addWidget(self.info_ppr_edit_label)
        self.info_who_edit_label = QtGui.QLabel(self.verticalLayoutWidget_122)
        self.info_who_edit_label.setObjectName(_fromUtf8("info_who_edit_label"))
        self.verticalLayout_94.addWidget(self.info_who_edit_label)
        self.verticalLayoutWidget_123 = QtGui.QWidget(self.info_edit_group)
        self.verticalLayoutWidget_123.setGeometry(QtCore.QRect(200, 20, 201, 151))
        self.verticalLayoutWidget_123.setObjectName(_fromUtf8("verticalLayoutWidget_123"))
        self.info_dir_input_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_123)
        self.info_dir_input_8.setMargin(0)
        self.info_dir_input_8.setObjectName(_fromUtf8("info_dir_input_8"))
        self.info_date_edit = QtGui.QLineEdit(self.verticalLayoutWidget_123)
        self.info_date_edit.setObjectName(_fromUtf8("info_date_edit"))
        self.info_dir_input_8.addWidget(self.info_date_edit)
        self.info_country_edit = QtGui.QLineEdit(self.verticalLayoutWidget_123)
        self.info_country_edit.setObjectName(_fromUtf8("info_country_edit"))
        self.info_dir_input_8.addWidget(self.info_country_edit)
        self.info_dir_edit = QtGui.QLineEdit(self.verticalLayoutWidget_123)
        self.info_dir_edit.setObjectName(_fromUtf8("info_dir_edit"))
        self.info_dir_input_8.addWidget(self.info_dir_edit)
        self.info_ppr_edit = QtGui.QLineEdit(self.verticalLayoutWidget_123)
        self.info_ppr_edit.setObjectName(_fromUtf8("info_ppr_edit"))
        self.info_dir_input_8.addWidget(self.info_ppr_edit)
        self.info_who_edit = QtGui.QLineEdit(self.verticalLayoutWidget_123)
        self.info_who_edit.setObjectName(_fromUtf8("info_who_edit"))
        self.info_dir_input_8.addWidget(self.info_who_edit)
        self.edit_reset = QtGui.QPushButton(self.tab_edit)
        self.edit_reset.setGeometry(QtCore.QRect(151, 504, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_reset.setFont(font)
        self.edit_reset.setObjectName(_fromUtf8("edit_reset"))
        self.edit_progressBar = QtGui.QProgressBar(self.tab_edit)
        self.edit_progressBar.setGeometry(QtCore.QRect(20, 543, 411, 20))
        self.edit_progressBar.setProperty("value", 0)
        self.edit_progressBar.setObjectName(_fromUtf8("edit_progressBar"))
        self.edit_write = QtGui.QPushButton(self.tab_edit)
        self.edit_write.setGeometry(QtCore.QRect(20, 504, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.edit_write.setFont(font)
        self.edit_write.setStyleSheet(_fromUtf8(""))
        self.edit_write.setObjectName(_fromUtf8("edit_write"))
        self.tmc_edit_group = QtGui.QGroupBox(self.tab_edit)
        self.tmc_edit_group.setGeometry(QtCore.QRect(440, 10, 331, 121))
        self.tmc_edit_group.setAutoFillBackground(True)
        self.tmc_edit_group.setObjectName(_fromUtf8("tmc_edit_group"))
        self.verticalLayoutWidget_18 = QtGui.QWidget(self.tmc_edit_group)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(10, 20, 91, 91))
        self.verticalLayoutWidget_18.setObjectName(_fromUtf8("verticalLayoutWidget_18"))
        self.tmc_label_group_input_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_18)
        self.tmc_label_group_input_2.setMargin(0)
        self.tmc_label_group_input_2.setObjectName(_fromUtf8("tmc_label_group_input_2"))
        self.sort_edit_label = QtGui.QLabel(self.verticalLayoutWidget_18)
        self.sort_edit_label.setObjectName(_fromUtf8("sort_edit_label"))
        self.tmc_label_group_input_2.addWidget(self.sort_edit_label)
        self.quant_edit_label = QtGui.QLabel(self.verticalLayoutWidget_18)
        self.quant_edit_label.setObjectName(_fromUtf8("quant_edit_label"))
        self.tmc_label_group_input_2.addWidget(self.quant_edit_label)
        self.price_edit_label = QtGui.QLabel(self.verticalLayoutWidget_18)
        self.price_edit_label.setObjectName(_fromUtf8("price_edit_label"))
        self.tmc_label_group_input_2.addWidget(self.price_edit_label)
        self.verticalLayoutWidget_19 = QtGui.QWidget(self.tmc_edit_group)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(240, 51, 81, 61))
        self.verticalLayoutWidget_19.setObjectName(_fromUtf8("verticalLayoutWidget_19"))
        self.tmc_group_input_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_19)
        self.tmc_group_input_2.setMargin(0)
        self.tmc_group_input_2.setObjectName(_fromUtf8("tmc_group_input_2"))
        self.quant_edit = QtGui.QLineEdit(self.verticalLayoutWidget_19)
        self.quant_edit.setObjectName(_fromUtf8("quant_edit"))
        self.tmc_group_input_2.addWidget(self.quant_edit)
        self.price_edit = QtGui.QLineEdit(self.verticalLayoutWidget_19)
        self.price_edit.setObjectName(_fromUtf8("price_edit"))
        self.tmc_group_input_2.addWidget(self.price_edit)
        self.verticalLayoutWidget_20 = QtGui.QWidget(self.tmc_edit_group)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(110, 51, 121, 61))
        self.verticalLayoutWidget_20.setObjectName(_fromUtf8("verticalLayoutWidget_20"))
        self.tmc_select_group_input_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_20)
        self.tmc_select_group_input_2.setMargin(0)
        self.tmc_select_group_input_2.setObjectName(_fromUtf8("tmc_select_group_input_2"))
        self.quant_edit_select = QtGui.QLineEdit(self.verticalLayoutWidget_20)
        self.quant_edit_select.setObjectName(_fromUtf8("quant_edit_select"))
        self.tmc_select_group_input_2.addWidget(self.quant_edit_select)
        self.price_edit_select = QtGui.QLineEdit(self.verticalLayoutWidget_20)
        self.price_edit_select.setObjectName(_fromUtf8("price_edit_select"))
        self.tmc_select_group_input_2.addWidget(self.price_edit_select)
        self.sort_edit = QtGui.QLineEdit(self.tmc_edit_group)
        self.sort_edit.setGeometry(QtCore.QRect(110, 20, 211, 25))
        self.sort_edit.setObjectName(_fromUtf8("sort_edit"))
        self.fab_edit_group = QtGui.QGroupBox(self.tab_edit)
        self.fab_edit_group.setGeometry(QtCore.QRect(440, 140, 331, 421))
        self.fab_edit_group.setAcceptDrops(False)
        self.fab_edit_group.setAutoFillBackground(True)
        self.fab_edit_group.setFlat(False)
        self.fab_edit_group.setCheckable(False)
        self.fab_edit_group.setObjectName(_fromUtf8("fab_edit_group"))
        self.fab_edit_text = QtGui.QPlainTextEdit(self.fab_edit_group)
        self.fab_edit_text.setGeometry(QtCore.QRect(10, 30, 311, 381))
        self.fab_edit_text.setObjectName(_fromUtf8("fab_edit_text"))
        self.edit_delete = QtGui.QPushButton(self.tab_edit)
        self.edit_delete.setGeometry(QtCore.QRect(270, 504, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.edit_delete.setFont(font)
        self.edit_delete.setStyleSheet(_fromUtf8(""))
        self.edit_delete.setObjectName(_fromUtf8("edit_delete"))
        self.allTabWidget.addTab(self.tab_edit, _fromUtf8(""))
        self.tab_admin = QtGui.QWidget()
        self.tab_admin.setObjectName(_fromUtf8("tab_admin"))
        self.admin_new_group = QtGui.QGroupBox(self.tab_admin)
        self.admin_new_group.setGeometry(QtCore.QRect(20, 10, 461, 261))
        self.admin_new_group.setAutoFillBackground(True)
        self.admin_new_group.setObjectName(_fromUtf8("admin_new_group"))
        self.verticalLayoutWidget_14 = QtGui.QWidget(self.admin_new_group)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(10, 20, 171, 151))
        self.verticalLayoutWidget_14.setObjectName(_fromUtf8("verticalLayoutWidget_14"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.admin_new_name_label = QtGui.QLabel(self.verticalLayoutWidget_14)
        self.admin_new_name_label.setObjectName(_fromUtf8("admin_new_name_label"))
        self.verticalLayout_6.addWidget(self.admin_new_name_label)
        self.admin_new_pass_label = QtGui.QLabel(self.verticalLayoutWidget_14)
        self.admin_new_pass_label.setObjectName(_fromUtf8("admin_new_pass_label"))
        self.verticalLayout_6.addWidget(self.admin_new_pass_label)
        self.admin_new_conf_pass_label = QtGui.QLabel(self.verticalLayoutWidget_14)
        self.admin_new_conf_pass_label.setObjectName(_fromUtf8("admin_new_conf_pass_label"))
        self.verticalLayout_6.addWidget(self.admin_new_conf_pass_label)
        self.verticalLayoutWidget_15 = QtGui.QWidget(self.admin_new_group)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(200, 20, 251, 151))
        self.verticalLayoutWidget_15.setObjectName(_fromUtf8("verticalLayoutWidget_15"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.admin_new_name = QtGui.QLineEdit(self.verticalLayoutWidget_15)
        self.admin_new_name.setObjectName(_fromUtf8("admin_new_name"))
        self.verticalLayout_7.addWidget(self.admin_new_name)
        self.admin_new_pass = QtGui.QLineEdit(self.verticalLayoutWidget_15)
        self.admin_new_pass.setObjectName(_fromUtf8("admin_new_pass"))
        self.verticalLayout_7.addWidget(self.admin_new_pass)
        self.admin_new_conf_pass = QtGui.QLineEdit(self.verticalLayoutWidget_15)
        self.admin_new_conf_pass.setObjectName(_fromUtf8("admin_new_conf_pass"))
        self.verticalLayout_7.addWidget(self.admin_new_conf_pass)
        self.admin_new_write = QtGui.QPushButton(self.admin_new_group)
        self.admin_new_write.setGeometry(QtCore.QRect(10, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_new_write.setFont(font)
        self.admin_new_write.setObjectName(_fromUtf8("admin_new_write"))
        self.admin_new_reset = QtGui.QPushButton(self.admin_new_group)
        self.admin_new_reset.setGeometry(QtCore.QRect(200, 180, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.admin_new_reset.setFont(font)
        self.admin_new_reset.setObjectName(_fromUtf8("admin_new_reset"))
        self.add_user_status_label = QtGui.QLabel(self.admin_new_group)
        self.add_user_status_label.setGeometry(QtCore.QRect(10, 220, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_user_status_label.setFont(font)
        self.add_user_status_label.setText(_fromUtf8(""))
        self.add_user_status_label.setObjectName(_fromUtf8("add_user_status_label"))
        self.admin_del_user_group = QtGui.QGroupBox(self.tab_admin)
        self.admin_del_user_group.setGeometry(QtCore.QRect(490, 10, 281, 261))
        self.admin_del_user_group.setAutoFillBackground(True)
        self.admin_del_user_group.setObjectName(_fromUtf8("admin_del_user_group"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.admin_del_user_group)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 261, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.admin_del_user_label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.admin_del_user_label.setFont(font)
        self.admin_del_user_label.setObjectName(_fromUtf8("admin_del_user_label"))
        self.horizontalLayout.addWidget(self.admin_del_user_label)
        self.admin_del_user_select = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.admin_del_user_select.setObjectName(_fromUtf8("admin_del_user_select"))
        self.horizontalLayout.addWidget(self.admin_del_user_select)
        self.admin_del_user = QtGui.QPushButton(self.admin_del_user_group)
        self.admin_del_user.setGeometry(QtCore.QRect(10, 140, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_del_user.setFont(font)
        self.admin_del_user.setObjectName(_fromUtf8("admin_del_user"))
        self.admin_del_user_pass_label = QtGui.QLabel(self.admin_del_user_group)
        self.admin_del_user_pass_label.setGeometry(QtCore.QRect(10, 70, 261, 21))
        self.admin_del_user_pass_label.setObjectName(_fromUtf8("admin_del_user_pass_label"))
        self.admin_del_user_pass_text = QtGui.QLineEdit(self.admin_del_user_group)
        self.admin_del_user_pass_text.setGeometry(QtCore.QRect(10, 100, 261, 31))
        self.admin_del_user_pass_text.setObjectName(_fromUtf8("admin_del_user_pass_text"))
        self.del_user_status_label = QtGui.QLabel(self.admin_del_user_group)
        self.del_user_status_label.setGeometry(QtCore.QRect(10, 215, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.del_user_status_label.setFont(font)
        self.del_user_status_label.setText(_fromUtf8(""))
        self.del_user_status_label.setObjectName(_fromUtf8("del_user_status_label"))
        self.admin_chahge_pass_group = QtGui.QGroupBox(self.tab_admin)
        self.admin_chahge_pass_group.setGeometry(QtCore.QRect(20, 290, 461, 271))
        self.admin_chahge_pass_group.setAutoFillBackground(True)
        self.admin_chahge_pass_group.setObjectName(_fromUtf8("admin_chahge_pass_group"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.admin_chahge_pass_group)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 261, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chahge_pass_sel_user_label = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chahge_pass_sel_user_label.setFont(font)
        self.chahge_pass_sel_user_label.setObjectName(_fromUtf8("chahge_pass_sel_user_label"))
        self.horizontalLayout_3.addWidget(self.chahge_pass_sel_user_label)
        self.admin_del_user_select_2 = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        self.admin_del_user_select_2.setObjectName(_fromUtf8("admin_del_user_select_2"))
        self.horizontalLayout_3.addWidget(self.admin_del_user_select_2)
        self.chahge_pass_user = QtGui.QPushButton(self.admin_chahge_pass_group)
        self.chahge_pass_user.setGeometry(QtCore.QRect(280, 26, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chahge_pass_user.setFont(font)
        self.chahge_pass_user.setObjectName(_fromUtf8("chahge_pass_user"))
        self.verticalLayoutWidget_16 = QtGui.QWidget(self.admin_chahge_pass_group)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(10, 70, 171, 151))
        self.verticalLayoutWidget_16.setObjectName(_fromUtf8("verticalLayoutWidget_16"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.chahge_pass_sel_user_old_label = QtGui.QLabel(self.verticalLayoutWidget_16)
        self.chahge_pass_sel_user_old_label.setObjectName(_fromUtf8("chahge_pass_sel_user_old_label"))
        self.verticalLayout_8.addWidget(self.chahge_pass_sel_user_old_label)
        self.chahge_pass_sel_user_new_label = QtGui.QLabel(self.verticalLayoutWidget_16)
        self.chahge_pass_sel_user_new_label.setObjectName(_fromUtf8("chahge_pass_sel_user_new_label"))
        self.verticalLayout_8.addWidget(self.chahge_pass_sel_user_new_label)
        self.chahge_pass_sel_user_conf_label = QtGui.QLabel(self.verticalLayoutWidget_16)
        self.chahge_pass_sel_user_conf_label.setObjectName(_fromUtf8("chahge_pass_sel_user_conf_label"))
        self.verticalLayout_8.addWidget(self.chahge_pass_sel_user_conf_label)
        self.verticalLayoutWidget_17 = QtGui.QWidget(self.admin_chahge_pass_group)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(200, 70, 251, 151))
        self.verticalLayoutWidget_17.setObjectName(_fromUtf8("verticalLayoutWidget_17"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.chahge_pass_sel_user_old = QtGui.QLineEdit(self.verticalLayoutWidget_17)
        self.chahge_pass_sel_user_old.setObjectName(_fromUtf8("chahge_pass_sel_user_old"))
        self.verticalLayout_9.addWidget(self.chahge_pass_sel_user_old)
        self.chahge_pass_sel_user_new = QtGui.QLineEdit(self.verticalLayoutWidget_17)
        self.chahge_pass_sel_user_new.setObjectName(_fromUtf8("chahge_pass_sel_user_new"))
        self.verticalLayout_9.addWidget(self.chahge_pass_sel_user_new)
        self.chahge_pass_sel_user_conf = QtGui.QLineEdit(self.verticalLayoutWidget_17)
        self.chahge_pass_sel_user_conf.setObjectName(_fromUtf8("chahge_pass_sel_user_conf"))
        self.verticalLayout_9.addWidget(self.chahge_pass_sel_user_conf)
        self.change_pass_status_label = QtGui.QLabel(self.admin_chahge_pass_group)
        self.change_pass_status_label.setGeometry(QtCore.QRect(10, 230, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.change_pass_status_label.setFont(font)
        self.change_pass_status_label.setText(_fromUtf8(""))
        self.change_pass_status_label.setObjectName(_fromUtf8("change_pass_status_label"))
        self.allTabWidget.addTab(self.tab_admin, _fromUtf8(""))
        self.tab_about = QtGui.QWidget()
        self.tab_about.setObjectName(_fromUtf8("tab_about"))
        self.about_label = QtGui.QLabel(self.tab_about)
        self.about_label.setGeometry(QtCore.QRect(20, 13, 351, 261))
        self.about_label.setText(_fromUtf8(""))
        self.about_label.setObjectName(_fromUtf8("about_label"))
        self.about_label_3 = QtGui.QLabel(self.tab_about)
        self.about_label_3.setGeometry(QtCore.QRect(413, 10, 351, 551))
        self.about_label_3.setText(_fromUtf8(""))
        self.about_label_3.setObjectName(_fromUtf8("about_label_3"))
        self.about_label_2 = QtGui.QLabel(self.tab_about)
        self.about_label_2.setGeometry(QtCore.QRect(20, 300, 351, 251))
        self.about_label_2.setText(_fromUtf8(""))
        self.about_label_2.setObjectName(_fromUtf8("about_label_2"))
        self.allTabWidget.addTab(self.tab_about, _fromUtf8(""))

        self.retranslateUi(main_window)
        self.allTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(_translate("main_window", "Персона_1.0", None))
        self.login_group.setTitle(_translate("main_window", "Вход в приложение", None))
        self.login_login_label.setText(_translate("main_window", "Введите логин", None))
        self.login_pass_label.setText(_translate("main_window", "Введите пароль", None))
        self.login_reset.setText(_translate("main_window", "Очистить", None))
        self.login_enter.setText(_translate("main_window", "Вход", None))
        self.allTabWidget.setTabText(self.allTabWidget.indexOf(self.tab_login), _translate("main_window", "Вход", None))
        self.pers_input_group.setTitle(_translate("main_window", "Личные данные", None))
        self.name_input_label.setText(_translate("main_window", "Имя (рус)", None))
        self.sur_input_label.setText(_translate("main_window", "Фамилия (рус)", None))
        self.name_lat_input_label.setText(_translate("main_window", "Имя (лат)", None))
        self.sur_lat_input_label.setText(_translate("main_window", "Фамилия (лат)", None))
        self.birth_input_label.setText(_translate("main_window", "Дата рождения", None))
        self.civil_input_label.setText(_translate("main_window", "Гражданство", None))
        self.pass_input_label.setText(_translate("main_window", "Номер паспорта", None))
        self.number_input_label.setText(_translate("main_window", "Личный номер", None))
        self.auto_input_label.setText(_translate("main_window", "Номер авто", None))
        self.info_input_group.setTitle(_translate("main_window", "Информация о задержании", None))
        self.info_date_input_label.setText(_translate("main_window", "Дата задержания", None))
        self.info_country_input_label.setText(_translate("main_window", "Сопред. государство", None))
        self.info_dir_input_label.setText(_translate("main_window", "Направление", None))
        self.info_ppr_input_label.setText(_translate("main_window", "Пункт пропуска", None))
        self.info_who_input_label.setText(_translate("main_window", "Ведомство", None))
        self.info_dir_input_in.setText(_translate("main_window", "Въезд", None))
        self.info_dir_input_out.setText(_translate("main_window", "Выезд", None))
        self.tmc_input_group.setTitle(_translate("main_window", "Информация о ТМЦ", None))
        self.sort_input_label.setText(_translate("main_window", "Вид", None))
        self.quant_input_label.setText(_translate("main_window", "Количество", None))
        self.price_input_label.setText(_translate("main_window", "Стоимость", None))
        self.fab_input_group.setTitle(_translate("main_window", "Описание правонарушения", None))
        self.input_write.setText(_translate("main_window", "Записать", None))
        self.input_reset.setText(_translate("main_window", "Очистить", None))
        self.allTabWidget.setTabText(self.allTabWidget.indexOf(self.tab_input), _translate("main_window", "Ввести данные", None))
        self.pers_output_group.setTitle(_translate("main_window", "Искать по фамилии", None))
        self.sur_output_label.setText(_translate("main_window", "Фамилия (рус)", None))
        self.sur_lat_output_label.setText(_translate("main_window", "Фамилия (лат)", None))
        self.output_data_group.setTitle(_translate("main_window", "Полученные данные", None))
        self.output_data_total_label.setText(_translate("main_window", "Всего найдено лиц:", None))
        self.output_data_sur_label.setText(_translate("main_window", "Выбрать по фамилии", None))
        self.output_find_ppr.setText(_translate("main_window", "Найти", None))
        self.pers_output_group_2.setTitle(_translate("main_window", "Искать по номеру паспорта или автомобиля", None))
        self.pass_output_label.setText(_translate("main_window", "Номер паспорта", None))
        self.auto_output_label.setText(_translate("main_window", "Номер авто", None))
        self.output_reset_ppr.setText(_translate("main_window", "Очистить", None))
        self.output_find_sur.setText(_translate("main_window", "Найти", None))
        self.output_reset_sur.setText(_translate("main_window", "Очистить", None))
        self.output_find_num.setText(_translate("main_window", "Найти", None))
        self.output_reset_num.setText(_translate("main_window", "Очистить", None))
        self.info_output_group_2.setTitle(_translate("main_window", "Искать по информации о задержании", None))
        self.info_date_output_label_from.setText(_translate("main_window", "Дата задержания (с)", None))
        self.info_date_output_label_to.setText(_translate("main_window", "Дата задержания (по)", None))
        self.info_ppr_output_label.setText(_translate("main_window", "Пункт пропуска", None))
        self.info_dir_output_label.setText(_translate("main_window", "Направление", None))
        self.info_dir_output_in.setText(_translate("main_window", "Въезд", None))
        self.info_dir_output_out.setText(_translate("main_window", "Выезд", None))
        self.output_find_all.setText(_translate("main_window", "Найти всех", None))
        self.output_reset_output.setText(_translate("main_window", "Очистить поле", None))
        self.output_export.setText(_translate("main_window", "Экспорт в Word", None))
        self.output_export_pdf.setText(_translate("main_window", "Экспорт в PDF", None))
        self.info_output_group_date.setTitle(_translate("main_window", "Искать по дате задержания", None))
        self.info_date_output_date_label_from.setText(_translate("main_window", "Дата задержания (с)", None))
        self.info_date_output_date_label_to.setText(_translate("main_window", "Дата задержания (по)", None))
        self.output_reset_date.setText(_translate("main_window", "Очистить", None))
        self.output_find_date.setText(_translate("main_window", "Найти", None))
        self.allTabWidget.setTabText(self.allTabWidget.indexOf(self.tab_output), _translate("main_window", "Найти данные", None))
        self.pers_edit_group.setTitle(_translate("main_window", "Личные данные", None))
        self.name_edit_label.setText(_translate("main_window", "Имя (рус)", None))
        self.sur_edit_label.setText(_translate("main_window", "Фамилия (рус)", None))
        self.name_lat_edit_label.setText(_translate("main_window", "Имя (лат)", None))
        self.sur_lat_edit_label.setText(_translate("main_window", "Фамилия (лат)", None))
        self.birth_edit_label.setText(_translate("main_window", "Дата рождения", None))
        self.civil_edit_label.setText(_translate("main_window", "Гражданство", None))
        self.pass_edit_label.setText(_translate("main_window", "Номер паспорта", None))
        self.number_edit_label.setText(_translate("main_window", "Личный номер", None))
        self.auto_edit_label.setText(_translate("main_window", "Номер авто", None))
        self.info_edit_group.setTitle(_translate("main_window", "Информация о задержании", None))
        self.info_date_edit_label.setText(_translate("main_window", "Дата задержания", None))
        self.info_country_edit_label.setText(_translate("main_window", "Сопред. государство", None))
        self.info_dir_edit_label.setText(_translate("main_window", "Направление", None))
        self.info_ppr_edit_label.setText(_translate("main_window", "Пункт пропуска", None))
        self.info_who_edit_label.setText(_translate("main_window", "Ведомство", None))
        self.edit_reset.setText(_translate("main_window", "Очистить", None))
        self.edit_write.setText(_translate("main_window", "Обновить", None))
        self.tmc_edit_group.setTitle(_translate("main_window", "Информация о ТМЦ", None))
        self.sort_edit_label.setText(_translate("main_window", "Вид", None))
        self.quant_edit_label.setText(_translate("main_window", "Количество", None))
        self.price_edit_label.setText(_translate("main_window", "Стоимость", None))
        self.fab_edit_group.setTitle(_translate("main_window", "Описание правонарушения", None))
        self.edit_delete.setText(_translate("main_window", "Удалить запись", None))
        self.allTabWidget.setTabText(self.allTabWidget.indexOf(self.tab_edit), _translate("main_window", "Редактировать данные", None))
        self.admin_new_group.setTitle(_translate("main_window", "Добавление пользователя", None))
        self.admin_new_name_label.setText(_translate("main_window", "Ввести логин", None))
        self.admin_new_pass_label.setText(_translate("main_window", "Ввести пароль", None))
        self.admin_new_conf_pass_label.setText(_translate("main_window", "Подтвердить пароль", None))
        self.admin_new_write.setText(_translate("main_window", "Добавить", None))
        self.admin_new_reset.setText(_translate("main_window", "Очистить форму", None))
        self.admin_del_user_group.setTitle(_translate("main_window", "Удаление пользователя", None))
        self.admin_del_user_label.setText(_translate("main_window", "Выбрать пользователя", None))
        self.admin_del_user.setText(_translate("main_window", "Удалить пользователя", None))
        self.admin_del_user_pass_label.setText(_translate("main_window", "Ввести пароль администратора:", None))
        self.admin_chahge_pass_group.setTitle(_translate("main_window", "Смена пароля", None))
        self.chahge_pass_sel_user_label.setText(_translate("main_window", "Выбрать пользователя", None))
        self.chahge_pass_user.setText(_translate("main_window", "Сменить пароль", None))
        self.chahge_pass_sel_user_old_label.setText(_translate("main_window", "Ввести старый пароль", None))
        self.chahge_pass_sel_user_new_label.setText(_translate("main_window", "Ввести новый пароль", None))
        self.chahge_pass_sel_user_conf_label.setText(_translate("main_window", "Подтвердить пароль", None))
        self.allTabWidget.setTabText(self.allTabWidget.indexOf(self.tab_admin), _translate("main_window", "Панель администратора", None))
        self.allTabWidget.setTabText(self.allTabWidget.indexOf(self.tab_about), _translate("main_window", "О программе", None))

